### ISSUE TITLE
Wouldn't be nicer if you contribute to existing python to js compiler projects? 

### ISSUE THREAD

**Issue by v3ss0n** [koehlma/jaspy#3]
This seems to be re-inventing a lot of thing that many have done.
Would be nice if efforts can be joined? This guy is doing good job at doing js vm in python : 
https://github.com/kovidgoyal/rapydscript-ng

Most feature complete one is 
https://github.com/secureosv/pythia

**Comment by koehlma** [comment]
I want to implement some very specific features others are not offering. These features like threading enforce a very specific architecture. To implement the same things in other Python-to-JS tools you need to rewrite most of them anyway, so I decided to write my own. But I am using modified code from the Brython project already, so I do not need to reinvent all the basic stuff.
